config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :login, 
  	                                            sign_out: :logout}


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist      
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

	    resources :questions, shallow: true do
	      resources :answers, shallow: true, except: :index
	    end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end  

  resources :badges, only: :index do
    get :rewards, on: :collection
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :test_passage_badges, dependent: :destroy
  has_many :test_passages, through: :test_passage_badges
  has_many :tests, through: :test_passages
  has_many :users, through: :test_passages

  validates :title, :rule, :image_path, presence: true
  validates :title, uniqueness: true


  module Rule
    FIRST_ATTEMPT = 0
    LEVEL = 1
    CATEGORY = 2

    DEF_IMAGE_FIRST_ATTEMPT = 
      'https://image.flaticon.com/icons/png/128/1579/1579491.png'.freeze
    DEF_IMAGE_LEVEL = 
      'https://image.flaticon.com/icons/png/128/1579/1579489.png'.freeze
    DEF_IMAGE_CATEGORY = 
      'https://image.flaticon.com/icons/png/128/1579/1579490.png'.freeze

    ALL = [FIRST_ATTEMPT, LEVEL, CATEGORY].freeze

    LABEL_BY_CODE = {
      FIRST_ATTEMPT => I18n.t('models.badge.rule.badge_label_of_first_attempt'),
      LEVEL => I18n.t('models.badge.rule.badge_label_of_level'),
      CATEGORY => I18n.t('models.badge.rule.badge_label_of_category')
    }

    NAME_BY_CODE = {
      FIRST_ATTEMPT => :first_attempt_rule,
      LEVEL => :level_rule,
      CATEGORY => :category_rule
    }.freeze

    def self.all
      ALL.collect { |i| OpenStruct.new(id: i, label: LABEL_BY_CODE[i]) }
    end
  end

  def rule_label
    Rule::LABEL_BY_CODE.fetch(rule, '')
  end

  def rule_name
    Rule::NAME_BY_CODE.fetch(rule)
  end

  def test
    test_passages.with_badges.first.test
  end

  def test_passage_badge(user)
    user.test_passage_badges.where(badge_id: id).first
  end

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[new edit]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      flash[:info] = t('.success')
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def destroy
    @badge.destroy
    flash[:info] = t('.success')
    redirect_to admin_badges_url
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      flash[:info] = t('.success')
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  private

  def set_categories
    @levels = '0, 1, 2, 3'
    @categories = Category.all
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image_path, :rule, :value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def rewards
    @badges = current_user.badges.group('id')
    render :index
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle" scope="row"><%= badge.title %></td>
  <td class="align-middle">
    <img src="<%= badge.image_path %>"width="48" height="48" alt="badge">
  </td>
  <td class="align-middle"><%= badge.rule_label %></td>
  <td class="align-middle">
    <%= link_to t('.show'), admin_badge_path(badge), 
                            class: 'btn btn-outline-primary btn-sm' %>
  </td>
  <td class="align-middle">
    <%= link_to t('.edit'), edit_admin_badge_path(badge), 
                            class: 'btn btn-outline-primary btn-sm' %>
  </td>
  <td class="align-middle">
    <%= link_to t('.delete'), admin_badge_path(badge), 
                              method: :delete, 
                              data: {confirm: t('.confirm')}, 
                              class: 'btn btn-outline-danger btn-sm' %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, badge], local: true) do |form| %>
  <%= render 'shared/errors', resource: badge %>

  <div class="form-group">
    <%= form.label :rule %>
    <%= form.collection_radio_buttons(:rule, 
                                      Badge::Rule.all, 
                                      :id, :label) do |rb| %>
      <div class="form-check">
        <%= rb.radio_button(class: "form-check-input") %>
        <%= rb.label(class: "form-check-label") %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :image_path %>
    <%= form.text_field :image_path, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :value %>
    <%= form.text_field :value, class: 'form-control' %>
  </div>

  <div class="form-group">
    <div> <%= t('.valid_values') %> </div>
    <div> <%= t('.levels') %> </div>
    <div> <%= @levels %> </div>
    <div> <%= t('.categories') %> </div>
    <% @categories.each do |category| %>
        <span><%= category.id %></span>
        <span><%= category.title %></span>
        <br>
    <% end %>
  </div>

  <div class="action_button">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/badges/_index.html.erb
<table class="table table-striped table-borderless">
  <thead>
  <tr>
    <th class="text-center"><%= t('.title') %></th>
    <th class="text-center"><%= t('.image') %></th>
    <th class="text-center"><%= t('.rule') %></th>
    <th class="text-center" colspan="3"><%= t('.actions') %></th>
  </tr>
  </thead>

  <tbody>
    <%= render badges %>
  </tbody>
</table>

app/views/admin/badges/edit.html.erb
<h1 class="page_caption mt-3"><%= t('.header') %></h1>

<div class="card">
  <div class="card-body">
    <%= render 'form', badge: @badge %>
  </div>
</div>

<p class="mb-3">
  <span class="navigation_link">
    <%= link_to t('.show'), 
                admin_badge_path(@badge), 
                class: 'btn btn-sm' %>
  </span>|
  <span class="navigation_link">
    <%= link_to t('.go_back'), 
                admin_badges_path, 
                class: 'btn btn-sm' %>
  </span>
</p>

app/views/admin/badges/index.html.erb
<h1 class="page_caption mt-3"><%= t('.header') %></h1>

<%= render 'index', badges: @badges %>

<p class="mb-3">
  <%= link_to t('.new'), new_admin_badge_path, class: 'btn btn-outline-secondary btn-sm' %>
</p>

app/views/admin/badges/new.html.erb
<h1 class="page_caption mt-3"><%= t('.header') %></h1>

<div class="card">
  <div class="card-body">
    <%= render 'form', badge: @badge %>
  </div>
</div>

<p class="mb-3">
  <%= link_to t('go_back'), admin_badges_path %>
</p>

app/views/admin/badges/show.html.erb
<h1 class="page_caption mt-3"><%= t('.header') %></h1>

<div class="card">
  <div class="card-body">
    <p class="card-text">
      <strong><%= t('.rule') %>:</strong>
      <%= @badge.rule_label %>
    </p>

    <p class="card-text">
      <strong><%= t('.image') %>:</strong>
      <%= @badge.image_path %>
      <br>
      <img src="<%= @badge.image_path %>"width="128" height="128" alt="badge">
    </p>

    <p class="card-text">
      <strong><%= t('.title') %>:</strong>
      <%= @badge.title %>
    </p>

    <p class="card-text">
      <strong><%= t('.value') %>:</strong>
      <%= @badge.value %>
    </p>
  </div>
</div>

<p class="mb-3">
  <span class="navigation_link">
    <%= link_to t('.edit'), 
                edit_admin_badge_path(@badge), 
                class: 'btn btn-sm' %>
  </span>|
  <span class="navigation_link">
    <%= link_to t('.go_back'), 
                admin_badges_path, 
                class: 'btn btn-sm' %>
  </span>
</p>