config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :login, 
  	                                            sign_out: :logout}


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist      
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

	    resources :questions, shallow: true do
	      resources :answers, shallow: true, except: :index
	    end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end  

  resources :badges, only: :index do
    get :rewards, on: :collection
  end
end

app/views/admin/_nav.html.erb
<div class="header navbar navbar-light bg-light">
  <div class="header_left">
    <div class="title navbar-brand">
      <%= link_to t('.tests_link'), root_path %>
      <span class="admin-caption">
        <%= t('.header') %>
      </span>   
      <%= link_to 'Gists', admin_gists_path %>
      <%= link_to t('.admin_badges'), admin_badges_path %>
    </div>
  </div>

  <div class="header_right">
    <div class="nav-admin user navbar-text">
      <b><%= t('.welcome_html', name: current_user.name) %></b> |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    </div>
  </div>
</div>