config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :login, 
  	                                            sign_out: :logout}


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist      
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

	    resources :questions, shallow: true do
	      resources :answers, shallow: true, except: :index
	    end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end  

  resources :badges, only: :index do
    get :rewards, on: :collection
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
  end

  def create
    message = params[:feedback_body]
    if message.blank?
      flash[:danger] = t('.error')
    else
      FeedbacksMailer.feedback_message(current_user, message).deliver_now
      flash[:success] = t('.success')
    end
    redirect_to new_feedback_url
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/new.html.erb
<h2 class="page_caption mt-3"><%= t('.header') %></h2>

<%= form_with(url: feedbacks_path, local: true) do |form| %>

  <div class="edit_text">
    <%= text_area_tag 'feedback_body', nil, rows: 7, cols: 80 %>
  </div>

  <div class="action_button">
    <%= form.submit t('.submit') %>
  </div>
<% end %>

<div class="py-1">
  <%= link_to t('.go_back'), 
              tests_path, 
              class: 'btn btn-light btn-lg btn-block' %>
</div>