config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :login, 
  	                                            sign_out: :logout}


  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist      
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

	    resources :questions, shallow: true do
	      resources :answers, shallow: true, except: :index
	    end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end  

  resources :badges, only: :index do
    get :rewards, on: :collection
  end
end

app/views/layouts/_footer.html.erb
<div class="footer mx-2">
  <small class="row">
    <span class="col text-left"><%= current_year %>, <%= t('.author') %>, 
      <%= github_url('TestGuru', 'https://github.com/rubygitflow/test-guru')%>
      — <%= t('.title') %>
    </span>
    <span class="col text-right"><%= t('.about') %> <%= thinknetica_url %>.
    </span>
  </small>
</div>

app/views/layouts/_nav.html.erb
<div class="header navbar navbar-light bg-light">
  <div class="header_left">
    <div class="title navbar-brand">
      <%= link_to t('.header'), root_path %>
      <% if user_signed_in? %>
        <% if current_user.admin? %>  
          <%= link_to t('.admin_link'), admin_tests_path, class: 'admin-caption' %>
        <% end %>   
        <% if action_name != 'new' %> 
          <%= link_to t('.feedback_link'), new_feedback_path %>
        <% end %>
        <%= link_to t('.rewards'), rewards_badges_path %>
        <%= link_to t('.badges'), badges_path %>
      <% end %>   
    </div>
  </div>

  <div class="header_right">
    <span class="user_menu navbar-text">
      <% if user_signed_in? %>
        <b><%= t('.welcome_html', name: current_user.name) %></b>
        <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to t('.login'), new_user_session_path  %>
        <%= link_to t('.registration'), new_user_registration_path  %>
      <% end %>
    </span>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.head') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application" %>
</head>

<body>
  <%= render 'admin/nav' %>
  <div class="container">
    <%= render 'shared/flash' %>

    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 
                            media: 'all', 
                            'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>